### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Earu** [Metastruct/PortalGun#1]
- [ ] zclipping on walls
- [ ] sometimes when firing on a valid surface you have to spam until it works
- [ ] missing texture around portals for some reason
- [ ] automounting the addon does not work (still have missing textures)
